### ISSUE TITLE
Remove python2 extensions

### ISSUE THREAD

**Issue by girst** [mopidy/website#18]
At this point it is very unlikely that any of the remaining extensions will be ported. I've had a look at all py2 backends, (web-)frontends and mixers: none\* \*\* of them have had any activity in years and bug reports have gone ignored.
\* except pimusixbox/mopidy-websettings, which is at least responding to tickets
\*\* mopidy-subsonic suggests Prior99/mopidy-subidy as a replacement.

These extensions make navigating the extension directory harder/confusing and might lead new users to install an old version of mopidy.

I propose removing them from /ext/ and /ext/dists/. In the same go, we can then remove the cluttered "python 3" labels. If an extension were to still get ported, re-adding it will be easy.

I'd happily compile a PR if this gets accepted.

- [x] replace -subsonic with -subidy
- [x] purge py2-only extensions from /_ext
- [x] remove green 'python3' label; rename yellow one to 'prerelease'
- [x] on /ext/dists/, remove py3 column and add 'prerelease' label where applicable

**Comment by jodal** [comment]
My plan has always been to purge the outdated extensions sometime in the future. I agree with your analysis that what remains probably won't be updated, so we might as well get started with the purge.

Pull requests, preferably multiple smaller ones, are very welcome!

I'd add a fifth point to your task list:

- [ ] Remove `python3: true` from all extensions, leaving only `python3: prerelease`. Python 3 is assumed for everything in the registry after the purge. Nothing new should be added without Python 3 support. Thus, this explicit label should be removed to reduce the noise.

**Comment by girst** [comment]
https://github.com/mopidy/website/pull/19
