### ISSUE TITLE
Raspberry pi pimusic box soundcloud modipy 401 unauthorised error (not just safari)

### ISSUE THREAD

**Issue by MATTBROOKER1973** [mopidy/website#5]
Hi all. I am trying to complete the modipy authentication process for soundcloud on PImusicbox and keep getting a “401 unauthorised” error message on the modipy page. I’ve read elsewhere this maybe a safari issue although I also get the error with chrome and Firefox. I did type an incorrect code into the modipy page (soundcloud user code) which I now can’t delete which maybe the problem? Please let me know if you know how to solve this! Thanks

**Comment by jodal** [comment]
The SoundCloud and Spotify OAuth flows on Mopidy.com has been heavily rewamped over the last month, so I assume this issue no longer applies.
